# Generated by Django 3.1.1 on 2020-11-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('fono', models.CharField(max_length=12)),
                ('mensaje', models.CharField(max_length=500)),
            ],
        ),
    ]
